import type { ProductExp } from '~/types/productExp'
import type { Category } from '~/types/category'
import { mockCategoryProducts } from '~/tests/mockData/mockCategoryProducts'
import { mockCategories } from '~/tests/mockData/mockCategories'

const categoryMatrix: Category[][] = [];
for(let i = 1; i < 10; i++) {
  const categories:Category[] = [];
  const categoryProducts = mockCategoryProducts.filter(item => item.product_id === i);
  for(const categoryProduct of categoryProducts) {
    const category = mockCategories.find(item => item.id === categoryProduct.category_id);
    if (category) categories.push(category);
  }
  categoryMatrix.push(categories);
}

export const mockProducts: ProductExp[] = [
  {
    id: 1,
    user_id: 2,
    name: '腕時計',
    brand: '',
    price: 15000,
    content: 'スタイリッシュなデザインのメンズ腕時計',
    img_filename: 'defaultImages/Armani+Mens+Clock.jpg',
    condition_index: 2,
    categories: categoryMatrix[0],
    is_favorite: false,
    favorites_count: 10,
    purchases_exists: true,
  },
  {
    id: 2,
    user_id: 2,
    name: 'HDD',
    brand: '',
    price: 5000,
    content: '高速で信頼性の高いハードディスク',
    img_filename: 'defaultImages/HDD+Hard+Disk.jpg',
    condition_index: 2,
    categories: [],
    is_favorite: false,
    favorites_count: 0,
    purchases_exists: true,
  },
  {
    id: 3,
    user_id: 1,
    name: '玉ねぎ3束',
    brand: '',
    price: 300,
    content: '新鮮な玉ねぎ3束のセット',
    img_filename: 'defaultImages/iLoveIMG+d.jpg',
    condition_index: 3,
    categories: [],
    is_favorite: false,
    favorites_count: 0,
    purchases_exists: false,
  },
  {
    id: 4,
    user_id: 1,
    name: '革靴',
    brand: '',
    price: 4000,
    content: 'クラシックなデザインの革靴',
    img_filename: 'defaultImages/Leather+Shoes+Product+Photo.jpg',
    condition_index: 4,
    categories: [],
    is_favorite: false,
    favorites_count: 0,
    purchases_exists: false,
  },
  {
    id: 5,
    user_id: 1,
    name: 'ノートPC',
    brand: '',
    price: 45000,
    content: '高性能なノートパソコン',
    img_filename: 'defaultImages/Living+Room+Laptop.jpg',
    condition_index: 1,
    categories: [],
    is_favorite: false,
    favorites_count: 0,
    purchases_exists: false,
  },
  {
    id: 6,
    user_id: 1,
    name: 'マイク',
    brand: '',
    price: 8000,
    content: '高音質のレコーディング用マイク',
    img_filename: 'defaultImages/Music+Mic+4632231.jpg',
    condition_index: 2,
    categories: [],
    is_favorite: false,
    favorites_count: 0,
    purchases_exists: false,
  },
  {
    id: 7,
    user_id: 2,
    name: 'ショルダーバッグ',
    brand: '',
    price: 3500,
    content: 'おしゃれなショルダーバッグ',
    img_filename: 'defaultImages/Purse+fashion+pocket.jpg',
    condition_index: 3,
    categories: [],
    is_favorite: false,
    favorites_count: 0,
    purchases_exists: true,
  },
  {
    id: 8,
    user_id: 2,
    name: 'タンブラー',
    brand: '',
    price: 500,
    content: '使いやすいタンブラー',
    img_filename: 'defaultImages/Tumbler+souvenir.jpg',
    condition_index: 4,
    categories: [],
    is_favorite: false,
    favorites_count: 0,
    purchases_exists: true,
  },
  {
    id: 9,
    user_id: 2,
    name: 'コーヒーミル',
    brand: '',
    price: 4000,
    content: '手動のコーヒーミル',
    img_filename: 'defaultImages/Waitress+with+Coffee+Grinder.jpg',
    condition_index: 1,
    categories: [],
    is_favorite: false,
    favorites_count: 0,
    purchases_exists: false,
  },
  {
    id: 10,
    user_id: 2,
    name: 'メイクセット',
    brand: '',
    price: 2500,
    content: '便利なメイクアップセット',
    img_filename: 'defaultImages/Makeup_set.jpg',
    condition_index: 2,
    categories: [],
    is_favorite: false,
    favorites_count: 0,
    purchases_exists: false,
  }
]